# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
project_name: k8n
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - static_build
    targets:
      - linux_arm64
      - linux_amd64
      - darwin_arm64
      - darwin_amd64
      - linux_arm_7
    ldflags:
      -  -X main.Version={{.Version}}
      -  -X main.Revision={{.ShortCommit}}
      -  -X main.BuildDate={{.CommitDate}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
  - title: Features
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 0
  - title: "Fixes"
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: Dependencies
    regexp: '^.*?chore\(deps\)??!?:.+$'
    order: 998
  - title: Others
    order: 999

release:
  footer: |
    ## Docker images

    - `docker pull ghcr.io/kbudde/{{.ProjectName}}:latest`
    - `docker pull ghcr.io/kbudde/{{.ProjectName}}:{{.Version}}`
    - `docker pull ghcr.io/kbudde/{{.ProjectName}}:{{.Major}}`
    - `docker pull kbudde/{{.ProjectName}}:latest`
    - `docker pull kbudde/{{.ProjectName}}:{{.Version}}`
    - `docker pull kbudde/{{.ProjectName}}:{{.Major}}`

dockers:
-
  goos: linux
  goarch: amd64
  image_templates:
    - "kbudde/{{.ProjectName}}:linux-amd64-{{.Version}}"
    - "ghcr.io/kbudde/{{.ProjectName}}:linux-amd64-{{.Version}}"
  use: buildx
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/kbudde/{{.ProjectName}}"
  - "--platform=linux/amd64"
-
  goos: linux
  goarch: arm64
  image_templates:
  - "kbudde/{{.ProjectName}}:linux-arm64-{{.Version}}"
  - "ghcr.io/kbudde/{{.ProjectName}}:linux-arm64-{{.Version}}"
  use: buildx
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/kbudde/{{.ProjectName}}"
  - "--platform=linux/arm64"

docker_manifests:
- # github
  name_template: ghcr.io/kbudde/{{.ProjectName}}:latest
  image_templates: &github_images
  - ghcr.io/kbudde/{{.ProjectName}}:linux-amd64-{{.Version}}
  - ghcr.io/kbudde/{{.ProjectName}}:linux-arm64-{{.Version}}
-
  name_template: ghcr.io/kbudde/{{.ProjectName}}:{{.Version}}
  image_templates: *github_images
-
  name_template: ghcr.io/kbudde/{{.ProjectName}}:{{.Major}}
  image_templates: *github_images
- # dockerhub
  name_template: kbudde/{{.ProjectName}}:latest
  image_templates: &docker_images
  - kbudde/{{.ProjectName}}:linux-amd64-{{.Version}}
  - kbudde/{{.ProjectName}}:linux-arm64-{{.Version}}
-
  name_template: kbudde/{{.ProjectName}}:{{.Version}}
  image_templates: *docker_images
-
  name_template: kbudde/{{.ProjectName}}:{{.Major}}
  image_templates: *docker_images
