#@ load("@ytt:data", "data")

#@ for ns in data.values.namespacesProd:
#@ for secret in data.values.prodSecrets:
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: #@ secret.metadata.name
  namespace: #@ ns.metadata.name
  labels:
    k8n.budd.ee/managed: "true"
    k8n.budd.ee/managed-by: k8n-secret-operator
    env: prod
data: #@ secret.data
#@ end
#@ end
