apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8n
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - watch
  - create
  - update
  - patch
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
# kaap is watching for pods after deployment
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
