apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8n
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8n
subjects:
- kind: ServiceAccount
  name: k8n
  namespace: k8n
