apiVersion: v1
kind: ConfigMap
metadata:
  name: k8n
data:
  config.yaml: |-
    #! This is the secret operator config
    apiVersion: k8n.budd.ee/v1beta
    kind: config
    metadata:
      name: secret-operator
    #! k8n will watch all resources listed in watchers
    watcher:
    #! watch for secrets in namespace prod-secrets with label k8n.budd.ee/secret-operator enabled
    #! and copy them to namespaces with label env=prod
    - name: prodSecrets
      apiVersion: v1
      kind: secrets
      selector: "k8n.budd.ee/secret-operator in (enabled, true)"
      namespace: prod-secrets

    #! Secrets will be copied to namespaces defined in this watcher
    - name: namespacesProd
      apiVersion: v1
      kind: namespaces
      selector: "env=prod"
      namespace: ""
  createSecrets.ytt.yaml: "#@ load(\"@ytt:data\", \"data\")\n\n#@ for ns in data.values.namespacesProd:\n#@
    for secret in data.values.prodSecrets:\n--- \napiVersion: v1\nkind: Secret\ntype:
    Opaque\nmetadata:\n  name: #@ secret.metadata.name\n  namespace:
    #@ ns.metadata.name\n  labels:\n    k8n.budd.ee/managed: \"true\"\n    k8n.budd.ee/managed-by:
    k8n-secret-operator\n    env: prod\ndata: #@ secret.data\n#@ end\n#@ end\n\n\n"
